### ISSUE TITLE
Delayed Initialization

### ISSUE THREAD

**Issue by Epiczzor** [vectary/pocsports-demo#1]
The API takes forever to respond, and when it finally does throws two errors from a GET and a POST request. regardless of these errors the code works fine, but 10-15 second load time is what is bothering me the most.

![Capture](https://user-images.githubusercontent.com/8940552/67379932-3b9d0300-f5a7-11e9-99e1-59fd21d61fd3.PNG)

**Comment by borgo** [comment]
Thanks for reporting, the fix is live, please try again.

**Comment by Epiczzor** [comment]
Hey its working correctly on https://pocsports-demo.vectary.now.sh/
could you update a change to the repo as well ?

**Comment by Epiczzor** [comment]
Hey thanks for the quick response, ive got it working now, Thanks !
